#!/bin/sh
case "$1" in
  start)
    echo "Запуск Flask..."
    /opt/bin/python3 /opt/bin/app.py &
    ;;
  stop)
    echo "Остановка Flask..."
    pkill -f "python3 /opt/bin/app.py"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Использование: $0 {start|stop|restart}"
    exit 1
esac
